# Generated by Django 3.0.4 on 2020-04-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_id', models.IntegerField()),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('old_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('short', models.CharField(blank=True, max_length=255, null=True)),
                ('num_doctor', models.CharField(blank=True, max_length=255, null=True)),
                ('num_master', models.CharField(blank=True, max_length=255, null=True)),
                ('num_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('num_lab', models.CharField(blank=True, max_length=255, null=True)),
                ('num_library', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'school_base_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('comprehensive_score', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_time', models.CharField(blank=True, max_length=100, null=True)),
                ('like_num', models.IntegerField(blank=True, null=True)),
                ('point_num', models.IntegerField(blank=True, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'school_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolContractArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.CharField(blank=True, max_length=255, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'school_contract_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolJobrate',
            fields=[
                ('school_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('postgraduate', models.CharField(blank=True, max_length=255, null=True)),
                ('abroad', models.CharField(blank=True, max_length=255, null=True)),
                ('female_num', models.CharField(blank=True, max_length=255, null=True)),
                ('men_num', models.CharField(blank=True, max_length=255, null=True)),
                ('men_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('female_rate', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'school_jobrate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolLowestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('province_id', models.IntegerField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'school_lowest_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolProvinceline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('province_id', models.IntegerField(blank=True, null=True)),
                ('highest_score', models.CharField(blank=True, max_length=255, null=True)),
                ('average_score', models.CharField(blank=True, max_length=255, null=True)),
                ('lowest_score', models.CharField(blank=True, max_length=255, null=True)),
                ('lowest_rank', models.CharField(blank=True, max_length=255, null=True)),
                ('provincial_line', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_type', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_lot', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'school_provinceline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(blank=True, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('rank_type', models.IntegerField(blank=True, null=True)),
                ('view_month', models.IntegerField(blank=True, null=True)),
                ('view_week', models.IntegerField(blank=True, null=True)),
                ('level_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('f211', models.IntegerField(blank=True, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('province_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nature_name', models.CharField(blank=True, max_length=255, null=True)),
                ('province_id', models.IntegerField(blank=True, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('f985', models.IntegerField(blank=True, null=True)),
                ('dual_class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('view_total_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school_rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(blank=True, null=True)),
                ('special_type', models.CharField(blank=True, max_length=255, null=True)),
                ('special_detail', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'school_special',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolUnitNature',
            fields=[
                ('school_id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_nature', models.CharField(blank=True, max_length=2000, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'school_unit_nature',
                'managed': False,
            },
        ),
    ]
